# APPLICATION NAME
spring.application.name=AI-Phishing-Detection-Backend

# SERVER CONFIGURATION
server.port=8080

# POSTGRESQL DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5432/phishing_db
spring.datasource.username=postgres
spring.datasource.password=shaikimran123!@#
spring.datasource.driver-class-name=org.postgresql.Driver

# HIKARI CONNECTION POOL
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

# JPA / HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JWT CONFIGURATION
jwt.secret=MySecureJWTSecretKeyForAIPhishingDetection2026System
jwt.expiration=86400000

# FRONTEND URL
frontend.url=http://localhost:3000

# CORS CONFIGURATION
spring.web.cors.allowed-origins=http://localhost:3000
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true


# GEMINI API KEY
gemini.api.key=AIzaSyDcKsBzLKrcIOdZ5rQ91dCHNqu1E-X2Txs

# STABLE WORKING MODEL
gemini.model=gemini-2.5-flash

# AI SETTINGS
gemini.temperature=0.2
gemini.max-output-tokens=1024

# STRIPE PAYMENT CONFIGURATION
stripe.secret.key={your stripe key}

# FILE UPLOAD LIMITS
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JACKSON CONFIGURATION
spring.jackson.serialization.fail-on-empty-beans=false

# SERVER COMPRESSION
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain
server.compression.min-response-size=1024

# ACTUATOR CONFIGURATION
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# APPLICATION LOGS
logging.level.com.phishing.backend=DEBUG

# GEMINI DEBUG LOGS
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.apache.http=DEBUG

# SECURITY LOGS
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.web.FilterChainProxy=INFO

# HIBERNATE SQL LOGS
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT LOGS
logging.level.io.jsonwebtoken=INFO

# SERVER ERROR DETAILS
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never